In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('sonardataset.csv')
df.shape

(208, 61)

In [3]:
df.head()

,x_1,x_2,x_3,x_4,x_5,x_6,x_7,x_8,x_9,x_10,...,x_52,x_53,x_54,x_55,x_56,x_57,x_58,x_59,x_60,Y
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   x_1     208 non-null    float64
 1   x_2     208 non-null    float64
 2   x_3     208 non-null    float64
 3   x_4     208 non-null    float64
 4   x_5     208 non-null    float64
 5   x_6     208 non-null    float64
 6   x_7     208 non-null    float64
 7   x_8     208 non-null    float64
 8   x_9     208 non-null    float64
 9   x_10    208 non-null    float64
 10  x_11    208 non-null    float64
 11  x_12    208 non-null    float64
 12  x_13    208 non-null    float64
 13  x_14    208 non-null    float64
 14  x_15    208 non-null    float64
 15  x_16    208 non-null    float64
 16  x_17    208 non-null    float64
 17  x_18    208 non-null    float64
 18  x_19    208 non-null    float64
 19  x_20    208 non-null    float64
 20  x_21    208 non-null    float64
 21  x_22    208 non-null    float64
 22  x_23    208 non-null    float64
 23  x_24    208 non-null    float64
 24  x_25    208 non-null    float64
 25  x_26    208 non-null    float64
 26  x_27    208 non-null    float64
 27  x_28    208 non-null    float64
 28  x_29    208 non-null    float64
 29  x_30    208 non-null    float64
 30  x_31    208 non-null    float64
 31  x_32    208 non-null    float64
 32  x_33    208 non-null    float64
 33  x_34    208 non-null    float64
 34  x_35    208 non-null    float64
 35  x_36    208 non-null    float64
 36  x_37    208 non-null    float64
 37  x_38    208 non-null    float64
 38  x_39    208 non-null    float64
 39  x_40    208 non-null    float64
 40  x_41    208 non-null    float64
 41  x_42    208 non-null    float64
 42  x_43    208 non-null    float64
 43  x_44    208 non-null    float64
 44  x_45    208 non-null    float64
 45  x_46    208 non-null    float64
 46  x_47    208 non-null    float64
 47  x_48    208 non-null    float64
 48  x_49    208 non-null    float64
 49  x_50    208 non-null    float64
 50  x_51    208 non-null    float64
 51  x_52    208 non-null    float64
 52  x_53    208 non-null    float64
 53  x_54    208 non-null    float64
 54  x_55    208 non-null    float64
 55  x_56    208 non-null    float64
 56  x_57    208 non-null    float64
 57  x_58    208 non-null    float64
 58  x_59    208 non-null    float64
 59  x_60    208 non-null    float64
 60  Y       208 non-null    object
dtypes: float64(60), object(1)
memory usage: 99.3+ KB

In [5]:
df.isna().sum().sum()

np.int64(0)

- there are no missing values

In [6]:
from sklearn.preprocessing import StandardScaler

In [7]:
ss = StandardScaler()

In [8]:
df_scaled = df.iloc[:,:-1].copy()

In [9]:
column_names = df_scaled.columns

In [10]:
column_names

Index(['x_1', 'x_2', 'x_3', 'x_4', 'x_5', 'x_6', 'x_7', 'x_8', 'x_9', 'x_10',
       'x_11', 'x_12', 'x_13', 'x_14', 'x_15', 'x_16', 'x_17', 'x_18', 'x_19',
       'x_20', 'x_21', 'x_22', 'x_23', 'x_24', 'x_25', 'x_26', 'x_27', 'x_28',
       'x_29', 'x_30', 'x_31', 'x_32', 'x_33', 'x_34', 'x_35', 'x_36', 'x_37',
       'x_38', 'x_39', 'x_40', 'x_41', 'x_42', 'x_43', 'x_44', 'x_45', 'x_46',
       'x_47', 'x_48', 'x_49', 'x_50', 'x_51', 'x_52', 'x_53', 'x_54', 'x_55',
       'x_56', 'x_57', 'x_58', 'x_59', 'x_60'],
      dtype='object')

In [11]:
df_scaled.head()

,x_1,x_2,x_3,x_4,x_5,x_6,x_7,x_8,x_9,x_10,...,x_51,x_52,x_53,x_54,x_55,x_56,x_57,x_58,x_59,x_60
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0232,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0125,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0033,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0241,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0156,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094

In [12]:
df_scaled = pd.DataFrame(ss.fit_transform(df_scaled), columns=column_names)

In [13]:
df_scaled["Y"] = df['Y']

Encode Target Variable

In [14]:
df_scaled['Y'] = df_scaled['Y'].map({'R': 0, 'M': 1})

In [15]:
df_scaled.head()

,x_1,x_2,x_3,x_4,x_5,x_6,x_7,x_8,x_9,x_10,...,x_52,x_53,x_54,x_55,x_56,x_57,x_58,x_59,x_60,Y
0,-0.399551,-0.040648,-0.026926,-0.715105,0.364456,-0.101253,0.521638,0.297843,1.125272,0.021186,...,-1.115432,-0.597604,0.680897,-0.295646,1.481635,1.763784,0.069870,0.171678,-0.658947,0
1,0.703538,0.421630,1.055618,0.323330,0.777676,2.607217,1.522625,2.510982,1.318325,0.588706,...,-0.522349,-0.256857,-0.843151,0.015503,1.901046,1.070732,-0.472406,-0.444554,-0.419852,0
2,-0.129229,0.601067,1.723404,1.172176,0.400545,2.093337,1.968770,2.852370,3.232767,3.066105,...,1.017585,0.836373,-0.197833,1.231812,2.827246,4.120162,1.309360,0.252761,0.257582,0
3,-0.835555,-0.648910,0.481740,-0.719414,-0.987079,-1.149364,-0.193816,-0.084747,-1.000852,-0.610469,...,-0.137365,-1.009341,0.557326,-0.111785,-0.161060,-0.488635,-0.549875,-0.639154,1.034640,0
4,2.050790,0.856537,0.111327,-0.312227,-0.292365,-0.672796,-0.013735,1.317299,1.510531,1.772220,...,-1.073812,-0.753780,-0.060532,0.241793,-1.174638,-0.107456,-0.487900,0.447361,0.576375,0

#### 2. Model Implementation

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
x = df_scaled.iloc[:, :-1]
y = df_scaled.iloc[:, -1]

In [18]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42, stratify=y)

In [19]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
# Build the ANN Model
model = Sequential()

model.add(Dense(32,
                activation='relu',
                input_shape=(60,)))

model.add(Dense(1,
                activation='sigmoid'))

C:\Users\Basavaraj M\AppData\Roaming\Python\Python313\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [21]:
# Compile the Model
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [23]:
# Train the Model
history = model.fit(
    x_train,
    y_train,
    epochs=100,
    batch_size=16,
    validation_split=0.2,
    verbose=1
)

Epoch 1/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - accuracy: 0.5227 - loss: 0.7567 - val_accuracy: 0.4118 - val_loss: 0.7694
Epoch 2/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5909 - loss: 0.6753 - val_accuracy: 0.4706 - val_loss: 0.6774
Epoch 3/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6364 - loss: 0.6083 - val_accuracy: 0.6176 - val_loss: 0.6185
Epoch 4/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7197 - loss: 0.5608 - val_accuracy: 0.6471 - val_loss: 0.5712
Epoch 5/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7652 - loss: 0.5241 - val_accuracy: 0.7059 - val_loss: 0.5412
Epoch 6/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8106 - loss: 0.4940 - val_accuracy: 0.7647 - val_loss: 0.5183
Epoch 7/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8258 - loss: 0.4706 - val_accuracy: 0.8235 - val_loss: 0.4912
Epoch 8/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8636 - loss: 0.4469 - val_accuracy: 0.8235 - val_loss: 0.4751
Epoch 9/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8788 - loss: 0.4292 - val_accuracy: 0.8824 - val_loss: 0.4592
Epoch 10/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8939 - loss: 0.4107 - val_accuracy: 0.8824 - val_loss: 0.4452
Epoch 11/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9015 - loss: 0.3945 - val_accuracy: 0.8824 - val_loss: 0.4347
Epoch 12/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9167 - loss: 0.3781 - val_accuracy: 0.9118 - val_loss: 0.4255
Epoch 13/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9167 - loss: 0.3620 - val_accuracy: 0.9412 - val_loss: 0.4167
Epoch 14/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9167 - loss: 0.3483 - val_accuracy: 0.9412 - val_loss: 0.4091
Epoch 15/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9167 - loss: 0.3345 - val_accuracy: 0.9412 - val_loss: 0.3994
Epoch 16/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9242 - loss: 0.3211 - val_accuracy: 0.9118 - val_loss: 0.3924
Epoch 17/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9318 - loss: 0.3087 - val_accuracy: 0.9118 - val_loss: 0.3878
Epoch 18/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9318 - loss: 0.2969 - val_accuracy: 0.9118 - val_loss: 0.3806
Epoch 19/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9318 - loss: 0.2861 - val_accuracy: 0.9118 - val_loss: 0.3751
Epoch 20/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9318 - loss: 0.2759 - val_accuracy: 0.9118 - val_loss: 0.3700
Epoch 21/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9318 - loss: 0.2657 - val_accuracy: 0.9118 - val_loss: 0.3654
Epoch 22/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9394 - loss: 0.2572 - val_accuracy: 0.8529 - val_loss: 0.3608
Epoch 23/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9394 - loss: 0.2475 - val_accuracy: 0.8529 - val_loss: 0.3608
Epoch 24/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9470 - loss: 0.2384 - val_accuracy: 0.8529 - val_loss: 0.3592
Epoch 25/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9470 - loss: 0.2298 - val_accuracy: 0.8529 - val_loss: 0.3579
Epoch 26/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9470 - loss: 0.2215 - val_accuracy: 0.8529 - val_loss: 0.3564
Epoch 27/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9470 - loss: 0.2139 - val_accuracy: 0.8529 - val_loss: 0.3553
Epoch 28/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9621 - loss: 0.2062 - val_accuracy: 0.8529 - val_loss: 0.3541
Epoch 29/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9621 - loss: 0.1991 - val_accuracy: 0.8529 - val_loss: 0.3524
Epoch 30/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9621 - loss: 0.1920 - val_accuracy: 0.8529 - val_loss: 0.3503
Epoch 31/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9621 - loss: 0.1852 - val_accuracy: 0.8529 - val_loss: 0.3498
Epoch 32/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9621 - loss: 0.1793 - val_accuracy: 0.8529 - val_loss: 0.3489
Epoch 33/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9621 - loss: 0.1730 - val_accuracy: 0.8529 - val_loss: 0.3491
Epoch 34/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9697 - loss: 0.1667 - val_accuracy: 0.8529 - val_loss: 0.3510
Epoch 35/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9697 - loss: 0.1607 - val_accuracy: 0.8529 - val_loss: 0.3511
Epoch 36/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9848 - loss: 0.1544 - val_accuracy: 0.8824 - val_loss: 0.3534
Epoch 37/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9848 - loss: 0.1489 - val_accuracy: 0.8824 - val_loss: 0.3533
Epoch 38/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9848 - loss: 0.1435 - val_accuracy: 0.8824 - val_loss: 0.3529
Epoch 39/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9848 - loss: 0.1379 - val_accuracy: 0.8824 - val_loss: 0.3532
Epoch 40/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9848 - loss: 0.1332 - val_accuracy: 0.8824 - val_loss: 0.3539
Epoch 41/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9848 - loss: 0.1283 - val_accuracy: 0.8529 - val_loss: 0.3542
Epoch 42/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9924 - loss: 0.1235 - val_accuracy: 0.8529 - val_loss: 0.3546
Epoch 43/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9924 - loss: 0.1193 - val_accuracy: 0.8529 - val_loss: 0.3554
Epoch 44/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9924 - loss: 0.1147 - val_accuracy: 0.8529 - val_loss: 0.3566
Epoch 45/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9924 - loss: 0.1107 - val_accuracy: 0.8529 - val_loss: 0.3598
Epoch 46/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9924 - loss: 0.1067 - val_accuracy: 0.8529 - val_loss: 0.3622
Epoch 47/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9924 - loss: 0.1028 - val_accuracy: 0.8529 - val_loss: 0.3624
Epoch 48/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0986 - val_accuracy: 0.8529 - val_loss: 0.3643
Epoch 49/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0965 - val_accuracy: 0.8529 - val_loss: 0.3706
Epoch 50/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0928 - val_accuracy: 0.8529 - val_loss: 0.3744
Epoch 51/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0887 - val_accuracy: 0.8529 - val_loss: 0.3769
Epoch 52/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0853 - val_accuracy: 0.8529 - val_loss: 0.3770
Epoch 53/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0822 - val_accuracy: 0.8529 - val_loss: 0.3773
Epoch 54/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0795 - val_accuracy: 0.8529 - val_loss: 0.3770
Epoch 55/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0768 - val_accuracy: 0.8529 - val_loss: 0.3795
Epoch 56/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0743 - val_accuracy: 0.8529 - val_loss: 0.3809
Epoch 57/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0718 - val_accuracy: 0.8529 - val_loss: 0.3812
Epoch 58/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0696 - val_accuracy: 0.8529 - val_loss: 0.3831
Epoch 59/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0671 - val_accuracy: 0.8529 - val_loss: 0.3847
Epoch 60/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0650 - val_accuracy: 0.8529 - val_loss: 0.3870
Epoch 61/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0628 - val_accuracy: 0.8529 - val_loss: 0.3881
Epoch 62/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0609 - val_accuracy: 0.8529 - val_loss: 0.3905
Epoch 63/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0591 - val_accuracy: 0.8529 - val_loss: 0.3924
Epoch 64/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0570 - val_accuracy: 0.8529 - val_loss: 0.3920
Epoch 65/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0552 - val_accuracy: 0.8529 - val_loss: 0.3941
Epoch 66/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0536 - val_accuracy: 0.8529 - val_loss: 0.3986
Epoch 67/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0521 - val_accuracy: 0.8529 - val_loss: 0.4017
Epoch 68/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0504 - val_accuracy: 0.8529 - val_loss: 0.4026
Epoch 69/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0487 - val_accuracy: 0.8529 - val_loss: 0.4019
Epoch 70/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0478 - val_accuracy: 0.8824 - val_loss: 0.4029
Epoch 71/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0462 - val_accuracy: 0.8824 - val_loss: 0.4059
Epoch 72/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0447 - val_accuracy: 0.8824 - val_loss: 0.4087
Epoch 73/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0432 - val_accuracy: 0.8824 - val_loss: 0.4129
Epoch 74/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0420 - val_accuracy: 0.8824 - val_loss: 0.4160
Epoch 75/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0406 - val_accuracy: 0.8824 - val_loss: 0.4200
Epoch 76/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0396 - val_accuracy: 0.8824 - val_loss: 0.4220
Epoch 77/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.0384 - val_accuracy: 0.8824 - val_loss: 0.4252
Epoch 78/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.0374 - val_accuracy: 0.8824 - val_loss: 0.4271
Epoch 79/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0362 - val_accuracy: 0.8824 - val_loss: 0.4290
Epoch 80/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0353 - val_accuracy: 0.8824 - val_loss: 0.4313
Epoch 81/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0343 - val_accuracy: 0.8824 - val_loss: 0.4338
Epoch 82/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.0334 - val_accuracy: 0.8824 - val_loss: 0.4353
Epoch 83/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0325 - val_accuracy: 0.8824 - val_loss: 0.4393
Epoch 84/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0317 - val_accuracy: 0.8824 - val_loss: 0.4415
Epoch 85/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0308 - val_accuracy: 0.8824 - val_loss: 0.4420
Epoch 86/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.0300 - val_accuracy: 0.8824 - val_loss: 0.4441
Epoch 87/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.0292 - val_accuracy: 0.8824 - val_loss: 0.4455
Epoch 88/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0284 - val_accuracy: 0.8824 - val_loss: 0.4477
Epoch 89/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0277 - val_accuracy: 0.8824 - val_loss: 0.4496
Epoch 90/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0270 - val_accuracy: 0.8824 - val_loss: 0.4508
Epoch 91/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0264 - val_accuracy: 0.8824 - val_loss: 0.4520
Epoch 92/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0258 - val_accuracy: 0.8824 - val_loss: 0.4537
Epoch 93/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.0251 - val_accuracy: 0.8824 - val_loss: 0.4544
Epoch 94/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0245 - val_accuracy: 0.8824 - val_loss: 0.4560
Epoch 95/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.0239 - val_accuracy: 0.8824 - val_loss: 0.4579
Epoch 96/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0234 - val_accuracy: 0.8824 - val_loss: 0.4634
Epoch 97/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0229 - val_accuracy: 0.8824 - val_loss: 0.4651
Epoch 98/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0224 - val_accuracy: 0.8824 - val_loss: 0.4672
Epoch 99/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0217 - val_accuracy: 0.8824 - val_loss: 0.4677
Epoch 100/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.0212 - val_accuracy: 0.8824 - val_loss: 0.4687

In [24]:
# Evaluate the Model
loss, accuracy = model.evaluate(x_test, y_test)

print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9048 - loss: 0.2513
Test Loss: 0.25126272439956665
Test Accuracy: 0.9047619104385376

In [25]:
predictions = model.predict(x_test)

# Convert probabilities into class labels
predicted_classes = (predictions > 0.5).astype(int)

print(predicted_classes[:10])

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step
[[0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]]

#### 3. Hyperparameter Tuning

In [28]:
from sklearn.model_selection import GridSearchCV
from scikeras.wrappers import KerasClassifier
from tensorflow.keras.optimizers import Adam

In [29]:
def create_model(neurons=32,
                 activation='relu',
                 learning_rate=0.001,
                 hidden_layers=1):

    model = Sequential()

    # First hidden layer
    model.add(Dense(neurons,
                    activation=activation,
                    input_shape=(60,)))

    # Additional hidden layers
    for _ in range(hidden_layers - 1):
        model.add(Dense(neurons,
                        activation=activation))

    # Output layer
    model.add(Dense(1,
                    activation='sigmoid'))

    optimizer = Adam(learning_rate=learning_rate)

    model.compile(
        optimizer=optimizer,
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

In [30]:
model = KerasClassifier(
    model=create_model,
    verbose=0
)

In [31]:
param_grid = {

    "model__neurons": [16, 32, 64],

    "model__hidden_layers": [1, 2],

    "model__activation": [
        "relu",
        "tanh"
    ],

    "model__learning_rate": [
        0.01,
        0.001
    ],

    "batch_size": [
        8,
        16
    ],

    "epochs": [
        50,
        100
    ]
}

In [33]:
grid = GridSearchCV(

    estimator=model,

    param_grid=param_grid,

    cv=5,

    scoring="accuracy",

    n_jobs=-1
)

grid_result = grid.fit(x_train, y_train)

C:\Users\Basavaraj M\AppData\Roaming\Python\Python313\site-packages\joblib\externals\loky\process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
C:\Users\Basavaraj M\AppData\Roaming\Python\Python313\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [34]:
print("Best Accuracy:", grid_result.best_score_)

print("Best Parameters:")

print(grid_result.best_params_)

Best Accuracy: 0.843850267379679
Best Parameters:
{'batch_size': 8, 'epochs': 100, 'model__activation': 'relu', 'model__hidden_layers': 2, 'model__learning_rate': 0.01, 'model__neurons': 32}

#### 4. Evaluation

In [35]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

In [37]:
# Best model from Grid Search
best_model = grid_result.best_estimator_

# Predict
y_pred_tuned = best_model.predict(x_test)

print("Tuned Model Performance")
print("-----------------------")

print("Accuracy :", accuracy_score(y_test, y_pred_tuned))
print("Precision:", precision_score(y_test, y_pred_tuned))
print("Recall   :", recall_score(y_test, y_pred_tuned))
print("F1-Score :", f1_score(y_test, y_pred_tuned))

Tuned Model Performance
-----------------------
Accuracy : 0.9285714285714286
Precision: 0.9130434782608695
Recall   : 0.9545454545454546
F1-Score : 0.9333333333333333

In [38]:
print("Classification Report")

print(classification_report(
    y_test,
    y_pred_tuned,
    target_names=["Rock","Mine"]
))

Classification Report
              precision    recall  f1-score   support

        Rock       0.95      0.90      0.92        20
        Mine       0.91      0.95      0.93        22

    accuracy                           0.93        42
   macro avg       0.93      0.93      0.93        42
weighted avg       0.93      0.93      0.93        42

A simple Artificial Neural Network was successfully implemented to classify sonar signals into Rock and Mine categories. The dataset was preprocessed using StandardScaler, split into training and testing sets, and used to train a baseline ANN.

To improve performance, a Grid Search with 5-fold cross-validation was conducted to tune key hyperparameters, including the number of hidden layers, neurons, activation functions, learning rate, batch size, and epochs. The tuned model consistently outperformed the baseline model across accuracy, precision, recall, and F1-score, demonstrating that systematic hyperparameter optimization enhances both predictive performance and generalization.

Overall, this implementation shows the importance of proper data preprocessing, careful model design, and structured hyperparameter tuning in developing effective neural network classifiers